[package]
name = "dookie_cli_client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dookie_cli_client"
path = "src/main.rs"

[dependencies]
confy = { workspace = true }
prost = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
cargo_metadata = { workspace = true }
